# Generated by Django 3.0.5 on 2020-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('delete_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DoneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('done_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('period', models.PositiveIntegerField()),
                ('rating', models.IntegerField(choices=[(0, '重要事項(優先處理'), (1, '手頭最重要的項目(當紅炸子雞項目)'), (2, '每天都堅持要做的事情(風雨無阻'), (3, '一般'), (4, '準一般'), (5, '今日緊急項目'), (6, '本周緊急項目'), (7, '本月緊急'), (8, '今日目標'), (9, '本周目標'), (10, '本月目標'), (11, '唯一重要的事情'), (12, '技術盞'), (13, '提醒')], default=0)),
                ('runtime', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
