# Generated by Django 3.0.5 on 2020-04-25 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.TextField(default='今天目標是:'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='period',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='runtime',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
