# Generated by Django 3.0.5 on 2020-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200425_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('create_time', 'last_edit', 'rating', 'content')},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='rating',
            field=models.IntegerField(choices=[(0, '重要事項(優先處理)'), (1, '手頭最重要的項目(當紅炸子雞項目)'), (2, '每天都堅持要做的事情(風雨無阻'), (3, '一般'), (4, '準一般'), (5, '今日緊急項目'), (6, '本周緊急項目'), (7, '本月緊急'), (8, '今日目標'), (9, '本周目標'), (10, '本月目標'), (11, '唯一重要的事情'), (12, '技術盞'), (13, '提醒')], default=0),
        ),
    ]
